We can create the dataframe in pandas in the following ways
1. Using a csv - pd.read_csv()
2. Using a excel - pd.read_excel("filepath/file.xslx", "sheet1")
3. using a dictonary u first creat the dictonary and then use it
4. using a tuple
5. using a list dictionary

there are many other ways also

In [24]:
import pandas as pd
df = pd.read_csv('C:/MY ALL/Analytics Study/Python/Pandas/panda_saving/weather.csv')
df.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [3]:
# df = pd.read_excel('C:/MY ALL/Analytics Study/Python/archive/weather.xlsx', sheet_name='Sheet1')
# df.head()

In [4]:
weather = {
    "MinTemp": [10, 15, 20, 25, 30],
    "MaxTemp": [20, 25, 30, 35, 40],
    "Rainfall": [0, 5, 10, 15, 20]
}

df = pd.DataFrame(weather)
df.head()

   MinTemp  MaxTemp  Rainfall
0       10       20         0
1       15       25         5
2       20       30        10
3       25       35        15
4       30       40        20

In [5]:
# list_dictionary
weather = [
    {"MinTemp": 10, "MaxTemp": 20, "Rainfall": 0},
    {"MinTemp": 15, "MaxTemp": 25, "Rainfall": 5},
    {"MinTemp": 20, "MaxTemp": 30, "Rainfall": 10},
    {"MinTemp": 25, "MaxTemp": 35, "Rainfall": 15},
    {"MinTemp": 30, "MaxTemp": 40, "Rainfall": 20}
]
df = pd.DataFrame(weather)  
df.head()

   MinTemp  MaxTemp  Rainfall
0       10       20         0
1       15       25         5
2       20       30        10
3       25       35        15
4       30       40        20

In [6]:
# list_tuple other way

weather = [
    {1,2,30},
    {4,5,60},
    {7,8,90}
]
df = pd.DataFrame(weather, columns=["MinTemp", "MaxTemp", "Rainfall"])  
df.head()

   MinTemp  MaxTemp  Rainfall
0        1        2        30
1        4        5        60
2        8       90         7

suppsoe we have a csv file and then we want to have its second row as header then
df = pd.read_csv("weather.csv", skiprows =1) - header at second row

suppose you dont have a header in that case, you can manuually add header or the code wil created header with number 0 and soon
df = pd.read_csv('weather.csv' header = none) - header with column name 0,1,2 and soon
df = pd.read_csv('weather.csv' header = none, Name = ['ticker', 'alpha']) - header with column name as given


suppose you want only top n rows excluding the header then
df = pd.read_csv ("weather.csv", nrows =3) - top 3 rows

replace NA with some values
df = pd.read_csv ("weather.csv", na_values = ['not available', 'n.a']) - whenever you get not available or na turn that into NAN

suppose you have a table where you have some messy data such as one column is there which contains -1 which can be converted to nan but there is another column where -1 is important in that case. we can pass a dictionary instead of a list to the na-value. eg

import pandas as pd

df = pd.read_csv(
    "data.csv",
    na_values={
        "Age":['not avialble', 'n.a',-1],
        "Salary": ['not avialble', 'n.a',-1]
    }
)

SAVING THE MODIFIED CSV FILE

In [ ]:
df.to_csv('C:\\MY ALL\\Analytics Study\\Python\\archive\\modified_weather.csv', index=False) # index=False means we don't want to write row numbers

In [ ]:
#save specific columns
df.to_csv('C:\\MY ALL\\Analytics Study\\Python\\archive\\modified_weather2.csv', columns=["MinTemp", "MaxTemp"], index=False) # only save specific columns

using Convertor to handle messy data
here we define a function and then use that function in the data frame line eg

In [ ]:
import pandas as pd
df = pd.read_csv('C:\\MY ALL\\Analytics Study\\Python\\archive\\modified_weather.csv')
df.head(5)

  MinTemp        MaxTemp  Rainfall
0       1              2        30
1       4              5        60
2       8             90         7
3     n.a  Not available        -1
4      -8             -9         0

In [ ]:
import pandas as pd
def convert_to_min(cell):
    if cell == "n.a":
        return None
    return cell

def convert_to_max(cell):
    if cell == "Not available":
        return None
    return cell

df = pd.read_csv('C:\\MY ALL\\Analytics Study\\Python\\archive\\modified_weather.csv',
                 converters={"MinTemp": convert_to_min, 
                             "MaxTemp": convert_to_max}  )
df.head(5)

  MinTemp MaxTemp  Rainfall
0       1       2        30
1       4       5        60
2       8      90         7
3     NaN     NaN        -1
4      -8      -9         0

In [ ]:
df.to_excel('C:\\MY ALL\\Analytics Study\\Python\\Pandas\\panda_saving\\modified_weather2.xlsx', startrow=2, startcol=3, index=False) # index=False means we don't want to write row numbers

In [ ]:
#want to give the offset of column and rows while saving to excel
df.to_excel('C:\\MY ALL\\Analytics Study\\Python\\Pandas\\panda_saving\\modified_weather2.xlsx', startrow=2, startcol=3, index=False) # index=False means we don't want to write row numbers

save two dfs in same xcel but different sheets

In [20]:
import pandas as pd

data1 = {
    "Name": ["A", "B", "C"],
    "Age": [20, 21, 22],
    "Marks": [80, 90, 85]
}

data2 = {
    "Name": ["D", "E", "F"],
    "Age": [23, 24, 25],
    "Marks": [75, 88, 92]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

print(df1)
print(df2)

  Name  Age  Marks
0    A   20     80
1    B   21     90
2    C   22     85
  Name  Age  Marks
0    D   23     75
1    E   24     88
2    F   25     92

In [23]:
with pd.ExcelWriter('C:\\MY ALL\\Analytics Study\\Python\\Pandas\\panda_saving\\multiple_sheets.xlsx') as writer:
    df1.to_excel(writer, sheet_name='Sheet1', index=False)
    df2.to_excel(writer, sheet_name='Sheet2', index=False)

MODIFY THE CSV FILE AND EDIT THE MISSING VALUES

In [56]:
import pandas as pd
weather = pd.read_csv('C:/MY ALL/Analytics Study/Python/Pandas/panda_saving/date_max_min_price.csv', parse_dates=["Date"])
weather.head()

         Date  Max Min   Price
0  01-01-2026   32  18   245.5
1  02-01-2026   34  19   251.2
2  03-01-2026   31  17  238.75
3  04-01-2026   29  16   230.4
4  05-01-2026   35  20   260.1

In [58]:
type(weather.Date[0] )

str

In [78]:
weather = pd.read_csv('C:/MY ALL/Analytics Study/Python/Pandas/panda_saving/date_max_min_price.csv', parse_dates=["Date"])
weather.head()

         Date  Max   Min   Price
0  01-01-2026   32  18.0  245.50
1  02-01-2026   34  19.0  251.20
2  03-01-2026   31  17.0  238.75
3  04-01-2026   29  16.0  230.40
4  05-01-2026   35  20.0  260.10

In [79]:
weather.dtypes

Date         str
Max        int64
Min      float64
Price    float64
dtype: object

In [80]:
weather["Date"] = pd.to_datetime(weather["Date"], format="%d-%m-%Y")

In [81]:
weather

         Date  Max   Min   Price
0  2026-01-01   32  18.0  245.50
1  2026-01-02   34  19.0  251.20
2  2026-01-03   31  17.0  238.75
3  2026-01-04   29  16.0  230.40
4  2026-01-05   35  20.0  260.10
5  2026-01-06   36  21.0  268.90
6  2026-01-07   33  19.0  255.30
7  2026-01-08   30  17.0  242.80
8  2026-01-09   28  15.0  225.60
9  2026-01-10   31   NaN  240.25
10 2026-01-11   34  20.0  258.70
11 2026-01-12   37  22.0  275.40
12 2026-01-13   35  21.0     NaN
13 2026-01-14   32  19.0  252.15
14 2026-01-15   29  16.0  235.90

In [82]:
weather.dtypes

Date     datetime64[us]
Max               int64
Min             float64
Price           float64
dtype: object

In [83]:
weather_new = weather.fillna(0)

In [84]:
weather_new.head(10)

        Date  Max   Min   Price
0 2026-01-01   32  18.0  245.50
1 2026-01-02   34  19.0  251.20
2 2026-01-03   31  17.0  238.75
3 2026-01-04   29  16.0  230.40
4 2026-01-05   35  20.0  260.10
5 2026-01-06   36  21.0  268.90
6 2026-01-07   33  19.0  255.30
7 2026-01-08   30  17.0  242.80
8 2026-01-09   28  15.0  225.60
9 2026-01-10   31   0.0  240.25

you can pass a dictionary in the fillna so that only specific columns get filled

In [95]:
weather_new.fillna({
    'price':0,
    'Max':0,
    'Min':1
})

         Date  Max   Min   Price
0  2026-01-01   32  18.0  245.50
1  2026-01-02   34  19.0  251.20
2  2026-01-03   31  17.0  238.75
3  2026-01-04   29  16.0  230.40
4  2026-01-05   35  20.0  260.10
5  2026-01-06   36  21.0  268.90
6  2026-01-07   33  19.0  255.30
7  2026-01-08   30  17.0  242.80
8  2026-01-09   28  15.0  225.60
9  2026-01-10   31   0.0  240.25
10 2026-01-11   34  20.0  258.70
11 2026-01-12   37  22.0  275.40
12 2026-01-13   35  21.0    0.00
13 2026-01-14   32  19.0  252.15
14 2026-01-15   29  16.0  235.90