we will modify and edit missing data or wrong values using Replace function

In [27]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:\\MY ALL\\Analytics Study\\Python\\Pandas\\panda_saving\\date_max_min_price.csv")
df

          Date   Max   Min    Price    Events
0   01-01-2026    32  18.0   245.50     Sunny
1   02-01-2026    34  19.0   251.20      Good
2   03-01-2026    31  17.0   238.75     Sunny
3   04-01-2026    29  16.0   230.40      Good
4   05-01-2026    35  20.0   260.10     Sunny
5   06-01-2026 -9999  21.0   268.90      Good
6   07-01-2026    33  19.0   255.30  No Event
7   08-01-2026    30  17.0   242.80      Good
8   09-01-2026    28  15.0 -9999.00     Sunny
9   10-01-2026    31   NaN   240.25  Good 677
10  11-01-2026    34  20.0   258.70     Sunny
11  12-01-2026    37  22.0   275.40      Good
12  13-01-2026    35  21.0      NaN     Sunny
13  14-01-2026    32  19.0   252.15      Good
14  15-01-2026    29  16.0 -9999.00     Sunny

In [28]:
new_df = df.replace(-9999, np.nan)
new_df

          Date   Max   Min   Price    Events
0   01-01-2026  32.0  18.0  245.50     Sunny
1   02-01-2026  34.0  19.0  251.20      Good
2   03-01-2026  31.0  17.0  238.75     Sunny
3   04-01-2026  29.0  16.0  230.40      Good
4   05-01-2026  35.0  20.0  260.10     Sunny
5   06-01-2026   NaN  21.0  268.90      Good
6   07-01-2026  33.0  19.0  255.30  No Event
7   08-01-2026  30.0  17.0  242.80      Good
8   09-01-2026  28.0  15.0     NaN     Sunny
9   10-01-2026  31.0   NaN  240.25  Good 677
10  11-01-2026  34.0  20.0  258.70     Sunny
11  12-01-2026  37.0  22.0  275.40      Good
12  13-01-2026  35.0  21.0     NaN     Sunny
13  14-01-2026  32.0  19.0  252.15      Good
14  15-01-2026  29.0  16.0     NaN     Sunny

In [29]:
new_df = df.replace([-9999, 19.0], np.nan)
new_df

          Date   Max   Min   Price    Events
0   01-01-2026  32.0  18.0  245.50     Sunny
1   02-01-2026  34.0   NaN  251.20      Good
2   03-01-2026  31.0  17.0  238.75     Sunny
3   04-01-2026  29.0  16.0  230.40      Good
4   05-01-2026  35.0  20.0  260.10     Sunny
5   06-01-2026   NaN  21.0  268.90      Good
6   07-01-2026  33.0   NaN  255.30  No Event
7   08-01-2026  30.0  17.0  242.80      Good
8   09-01-2026  28.0  15.0     NaN     Sunny
9   10-01-2026  31.0   NaN  240.25  Good 677
10  11-01-2026  34.0  20.0  258.70     Sunny
11  12-01-2026  37.0  22.0  275.40      Good
12  13-01-2026  35.0  21.0     NaN     Sunny
13  14-01-2026  32.0   NaN  252.15      Good
14  15-01-2026  29.0  16.0     NaN     Sunny

but sometimes replacing the  value is not the corrcet method as some row could have value which are correct for that case.
eg - replacing -1 will remove all -1 but -1 can be significant in some columns\
we solve this problem using dictionary

In [30]:
new_df = df.replace({
    'Max': -9999,
    'Min': 19.0,
    'Events': 'No Event'
}, np.nan)
new_df

          Date   Max   Min    Price    Events
0   01-01-2026  32.0  18.0   245.50     Sunny
1   02-01-2026  34.0   NaN   251.20      Good
2   03-01-2026  31.0  17.0   238.75     Sunny
3   04-01-2026  29.0  16.0   230.40      Good
4   05-01-2026  35.0  20.0   260.10     Sunny
5   06-01-2026   NaN  21.0   268.90      Good
6   07-01-2026  33.0   NaN   255.30       NaN
7   08-01-2026  30.0  17.0   242.80      Good
8   09-01-2026  28.0  15.0 -9999.00     Sunny
9   10-01-2026  31.0   NaN   240.25  Good 677
10  11-01-2026  34.0  20.0   258.70     Sunny
11  12-01-2026  37.0  22.0   275.40      Good
12  13-01-2026  35.0  21.0      NaN     Sunny
13  14-01-2026  32.0   NaN   252.15      Good
14  15-01-2026  29.0  16.0 -9999.00     Sunny

replacing  with mapping

In [31]:
new_df = df.replace({
     -9999:np.nan,
    19.0: np.nan,
    'No Event': 'very good'
})
new_df

          Date   Max   Min   Price     Events
0   01-01-2026  32.0  18.0  245.50      Sunny
1   02-01-2026  34.0   NaN  251.20       Good
2   03-01-2026  31.0  17.0  238.75      Sunny
3   04-01-2026  29.0  16.0  230.40       Good
4   05-01-2026  35.0  20.0  260.10      Sunny
5   06-01-2026   NaN  21.0  268.90       Good
6   07-01-2026  33.0   NaN  255.30  very good
7   08-01-2026  30.0  17.0  242.80       Good
8   09-01-2026  28.0  15.0     NaN      Sunny
9   10-01-2026  31.0   NaN  240.25   Good 677
10  11-01-2026  34.0  20.0  258.70      Sunny
11  12-01-2026  37.0  22.0  275.40       Good
12  13-01-2026  35.0  21.0     NaN      Sunny
13  14-01-2026  32.0   NaN  252.15       Good
14  15-01-2026  29.0  16.0     NaN      Sunny

using regexp to convert the expersion values into correct values on specific columns

In [33]:
new_df = df.replace({
        'Events': '[0-9]+'
    },'', regex=True
)
new_df

          Date   Max   Min    Price    Events
0   01-01-2026    32  18.0   245.50     Sunny
1   02-01-2026    34  19.0   251.20      Good
2   03-01-2026    31  17.0   238.75     Sunny
3   04-01-2026    29  16.0   230.40      Good
4   05-01-2026    35  20.0   260.10     Sunny
5   06-01-2026 -9999  21.0   268.90      Good
6   07-01-2026    33  19.0   255.30  No Event
7   08-01-2026    30  17.0   242.80      Good
8   09-01-2026    28  15.0 -9999.00     Sunny
9   10-01-2026    31   NaN   240.25     Good
10  11-01-2026    34  20.0   258.70     Sunny
11  12-01-2026    37  22.0   275.40      Good
12  13-01-2026    35  21.0      NaN     Sunny
13  14-01-2026    32  19.0   252.15      Good
14  15-01-2026    29  16.0 -9999.00     Sunny

In [35]:
import pandas as pd

data = {
    "Student": ["Rahul", "Priya", "Aman", "Sneha", "Rohit", "Ananya", "Vikas", "Neha"],
    "Grade": [ "Good", "Exceptional", "Average","Bad","Good","Exceptional","Poor","Average"]
}

df = pd.DataFrame(data)

df

  Student        Grade
0   Rahul         Good
1   Priya  Exceptional
2    Aman      Average
3   Sneha          Bad
4   Rohit         Good
5  Ananya  Exceptional
6   Vikas         Poor
7    Neha      Average

In [36]:
new_df = df.replace(
    {
        "Grade": {
            "Good": "A",
            "Exceptional": "A+",
            "Average": "B",
            "Bad": "C",
            "Poor": "D"
        }
    }
)
new_df

  Student Grade
0   Rahul     A
1   Priya    A+
2    Aman     B
3   Sneha     C
4   Rohit     A
5  Ananya    A+
6   Vikas     D
7    Neha     B