merge acts as Join here we can use the how act as key allowing inner, outer, left

In [2]:
import pandas as pd
India_weather = pd.DataFrame( {
    "city": ['Bihar','Delhi', 'Mumbai'],
    "temprature":[ 35, 40, 30]})
India_weather

     city  temprature
0   Bihar          35
1   Delhi          40
2  Mumbai          30

In [4]:
India_humidity = pd.DataFrame( {
    "city": ['Bihar','Delhi', 'Mumbai'],
    "Humidity":[ 65,40, 90],})
India_humidity

     city  Humidity
0   Bihar        65
1   Delhi        40
2  Mumbai        90

In [6]:

pd.merge(India_weather, India_humidity, on ='city', how= 'outer')

     city  temprature  Humidity
0   Bihar          35        65
1   Delhi          40        40
2  Mumbai          30        90

In [7]:
pd.merge(India_weather, India_humidity, on ='city', how= 'inner')

     city  temprature  Humidity
0   Bihar          35        65
1   Delhi          40        40
2  Mumbai          30        90

In [8]:
#  you can use indicator column to tell which data come from which tabloe
pd.merge(India_weather, India_humidity, on ='city', how= 'inner', indicator= True)

     city  temprature  Humidity _merge
0   Bihar          35        65   both
1   Delhi          40        40   both
2  Mumbai          30        90   both

In [16]:
import pandas as pd
May_weather = pd.DataFrame( {
    "city": ['Bihar','Delhi', 'Mumbai'],
    "temprature":[ 35, 40, 30],
    "humidity":[ 65, 50, 80]
})
May_weather

     city  temprature  humidity
0   Bihar          35        65
1   Delhi          40        50
2  Mumbai          30        80

In [17]:
import pandas as pd
June_weather = pd.DataFrame( {
    "city": ['Bihar','Delhi', 'Mumbai'],
    "temprature":[ 45, 30, 20],
    "humidity":[ 55, 60, 70]
})
June_weather

     city  temprature  humidity
0   Bihar          45        55
1   Delhi          30        60
2  Mumbai          20        70

In [18]:
df = pd.merge(May_weather, June_weather, on = 'city', suffixes=('_May',"_June"))
df

     city  temprature_May  humidity_May  temprature_June  humidity_June
0   Bihar              35            65               45             55
1   Delhi              40            50               30             60
2  Mumbai              30            80               20             70