Here we will deal with period data, which is a dataset of a given timeframe.

In [ ]:
# let us create a period

import pandas as pd
y = pd.Period('2026')
y

# Y - means annual and dec means ending in december. So this period represents the year 2026, which starts on January 1, 2026 and ends on December 31, 2026. The frequency of this period is annual, which means that it represents a single year.

Period('2026', 'Y-DEC')

In [15]:
dir(y)

['__add__',
 '__array_priority__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_cython__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__setstate__',
 '__setstate_cython__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__weakref__',
 '_add_offset',
 '_add_timedeltalike_scalar',
 '_dtype',
 '_freq',
 '_from_ordinal',
 '_maybe_convert_freq',
 '_module_source',
 '_ordinal',
 '_require_matching_freq',
 'asfreq',
 'day',
 'day_of_week',
 'day_of_year',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'end_time',
 'freq',
 'freqstr',
 'hour',
 'is_leap_year',
 'minute',
 'month',
 'now',
 'ordinal',
 'quarter',
 'qyear',
 'second',
 'start_time',
 'strftime',
 'to_timestamp',
 'week',
 'weekday',
 'weekofyear',
 'year']

In [ ]:
# check start and end time

y.start_time

Timestamp('2026-12-31 23:59:59.999999')

In [6]:
y.end_time

Timestamp('2026-12-31 23:59:59.999999')

In [ ]:
# crate a period with month frequency
m = pd.Period('2026-01', freq='M')
m

Period('2026-02', 'M')

In [11]:
m2 = m+1 # it takes you to the next month
m2

Period('2026-02', 'M')

In [13]:
# daily timeperiod
d= pd.Period('2026-01-01', freq='D')
d

Period('2026-01-01', 'D')

In [19]:
h = pd.Period('2026-12-31 23:59:59.999999', freq='h')
h

Period('2026-12-31 23:00', 'h')

In [20]:
h+1

Period('2027-01-01 00:00', 'h')

In [21]:
# do the same task using offset
h + pd.offsets.Hour(1)

Period('2027-01-01 00:00', 'h')

Quaterly periods

In [22]:
q = pd.Period('2026Q1', freq='Q')
q

Period('2026Q1', 'Q-DEC')

In [23]:
q+1

Period('2026Q2', 'Q-DEC')

In [24]:
q.start_time

Timestamp('2026-01-01 00:00:00')

In [ ]:
# we can have cases where the quater starts in feb or any other month rather than jan. In that case we can use the freq parameter to specify the starting month of the quarter. For example, if we want to create a period for the first quarter of 2026 that starts in February, we can use the following code:
q2 = pd.Period('2026Q1', freq='Q-JAN')
q2
# here freq = 'Q-JAN' means that the quarter ends in January, so the first quarter of 2026 starts on February 1, 2026 and ends on April 30, 2026.

Period('2026Q1', 'Q-JAN')

In [38]:
q2.start_time

Timestamp('2025-02-01 00:00:00')

In [ ]:
q2.end_time #end time of the quarter1 of 2026 is 30 april 2026, its because we have

Timestamp('2025-04-30 23:59:59.999999')

#change frequency

In [ ]:
q.asfreq('M', how='end') # this will give the start of the month for the quarter

# "Take this same time period, but express it using a monthly frequency, 
# and give me the last month of that period."

Period('2026-03', 'M')

In [46]:
q3 = pd.Period('2026Q4', freq='Q-JAN')

In [ ]:
q2-q3 #you can do this to get the difference between two periods.
#you can do this only when the q2 and q3 have the same frequency.

<-3 * QuarterEnds: startingMonth=1>

Period Index - peiods can be used as a index in Dataframes

Think of period_range() as:

"Start at this period and keep moving by one quarter until you reach the ending period."

In [50]:
idx = pd.period_range('2026-01', '2026-12', freq='Q')
idx

PeriodIndex(['2026Q1', '2026Q2', '2026Q3', '2026Q4'], dtype='period[Q-DEC]')

In [ ]:
idx = pd.period_range('2016', '2026', freq='Q')
idx

# here fiscal year is from jan to dec and  hence 2016 Q1 is first entrance

PeriodIndex(['2016Q1', '2016Q2', '2016Q3', '2016Q4', '2017Q1', '2017Q2',
             '2017Q3', '2017Q4', '2018Q1', '2018Q2', '2018Q3', '2018Q4',
             '2019Q1', '2019Q2', '2019Q3', '2019Q4', '2020Q1', '2020Q2',
             '2020Q3', '2020Q4', '2021Q1', '2021Q2', '2021Q3', '2021Q4',
             '2022Q1', '2022Q2', '2022Q3', '2022Q4', '2023Q1', '2023Q2',
             '2023Q3', '2023Q4', '2024Q1', '2024Q2', '2024Q3', '2024Q4',
             '2025Q1', '2025Q2', '2025Q3', '2025Q4', '2026Q1'],
            dtype='period[Q-DEC]')

In [ ]:
idx = pd.period_range('2016', '2026', freq='Q-JAN')
idx

# here fiscal year is from feb to dec and  hence it interprets the year 2016 as the fiscal year ending in January 2016. so the
# first quarter of the fiscal year 2016 is from February 1, 2015 to April 30, 2015, and the last quarter of the fiscal year 2026 is from November 1, 2025 to January 31, 2026.
# the january quarter is starting of our series because we have started from 2016 (jan) which is intself the q4

PeriodIndex(['2016Q4', '2017Q1', '2017Q2', '2017Q3', '2017Q4', '2018Q1',
             '2018Q2', '2018Q3', '2018Q4', '2019Q1', '2019Q2', '2019Q3',
             '2019Q4', '2020Q1', '2020Q2', '2020Q3', '2020Q4', '2021Q1',
             '2021Q2', '2021Q3', '2021Q4', '2022Q1', '2022Q2', '2022Q3',
             '2022Q4', '2023Q1', '2023Q2', '2023Q3', '2023Q4', '2024Q1',
             '2024Q2', '2024Q3', '2024Q4', '2025Q1', '2025Q2', '2025Q3',
             '2025Q4', '2026Q1', '2026Q2', '2026Q3', '2026Q4'],
            dtype='period[Q-JAN]')

In [53]:
idx.start_time

DatetimeIndex(['2015-11-01', '2016-02-01', '2016-05-01', '2016-08-01',
               '2016-11-01', '2017-02-01', '2017-05-01', '2017-08-01',
               '2017-11-01', '2018-02-01', '2018-05-01', '2018-08-01',
               '2018-11-01', '2019-02-01', '2019-05-01', '2019-08-01',
               '2019-11-01', '2020-02-01', '2020-05-01', '2020-08-01',
               '2020-11-01', '2021-02-01', '2021-05-01', '2021-08-01',
               '2021-11-01', '2022-02-01', '2022-05-01', '2022-08-01',
               '2022-11-01', '2023-02-01', '2023-05-01', '2023-08-01',
               '2023-11-01', '2024-02-01', '2024-05-01', '2024-08-01',
               '2024-11-01', '2025-02-01', '2025-05-01', '2025-08-01',
               '2025-11-01'],
              dtype='datetime64[us]', freq='QS-NOV')

QUESTION

In [62]:
import pandas as pd

df = pd.DataFrame({
    "Line Item": ["Revenue", "Expense", "Profit"],
    "2025Q1": [100000, 70000, 30000],
    "2025Q2": [120000, 80000, 40000],
    "2025Q3": [130000, 85000, 45000],
    "2025Q4": [150000, 90000, 60000],
    "2026Q1": [170000, 100000, 70000]
})

df

  Line Item  2025Q1  2025Q2  2025Q3  2025Q4  2026Q1
0   Revenue  100000  120000  130000  150000  170000
1   Expense   70000   80000   85000   90000  100000
2    Profit   30000   40000   45000   60000   70000

In [63]:
df.set_index('Line Item', inplace=True)
df

           2025Q1  2025Q2  2025Q3  2025Q4  2026Q1
Line Item
Revenue    100000  120000  130000  150000  170000
Expense     70000   80000   85000   90000  100000
Profit      30000   40000   45000   60000   70000

In [64]:
df= df.T
df

Line Item  Revenue  Expense  Profit
2025Q1      100000    70000   30000
2025Q2      120000    80000   40000
2025Q3      130000    85000   45000
2025Q4      150000    90000   60000
2026Q1      170000   100000   70000

In [65]:
df.index 
# here the index is a string, we can convert it to a period index using the pd.PeriodIndex() function. We can also specify the frequency of the period index using the freq parameter. In this case, we want to use a quarterly frequency, so we set freq='Q'.

Index(['2025Q1', '2025Q2', '2025Q3', '2025Q4', '2026Q1'], dtype='str')

In [68]:
df.index = pd.PeriodIndex(df.index, freq='Q')
df.index

PeriodIndex(['2025Q1', '2025Q2', '2025Q3', '2025Q4', '2026Q1'], dtype='period[Q-DEC]')

In [70]:
df['start_date']= df.index.map(lambda x: x.start_time)
df

Line Item  Revenue  Expense  Profit start_date
2025Q1      100000    70000   30000 2025-01-01
2025Q2      120000    80000   40000 2025-04-01
2025Q3      130000    85000   45000 2025-07-01
2025Q4      150000    90000   60000 2025-10-01
2026Q1      170000   100000   70000 2026-01-01

In [74]:
df['end_date'] = df.index.map(lambda x: x.end_time.date())
df

Line Item  Revenue  Expense  Profit start_date    end_date
2025Q1      100000    70000   30000 2025-01-01  2025-03-31
2025Q2      120000    80000   40000 2025-04-01  2025-06-30
2025Q3      130000    85000   45000 2025-07-01  2025-09-30
2025Q4      150000    90000   60000 2025-10-01  2025-12-31
2026Q1      170000   100000   70000 2026-01-01  2026-03-31