In [23]:
import pandas as pd

df = pd.DataFrame({
    'Price': [78.88, 75.88, 73.88, 72.88, 71.88, 71.88]
}, index=pd.to_datetime([
    '2025-01-01 09:30:00',
    '2025-01-02 09:30:00',
    '2025-01-03 09:30:00',
    '2025-01-04 09:30:00',
    '2025-01-05 09:30:00',
    '2025-01-06 09:30:00'
]))

df.index.name = 'Date'

df

                     Price
Date
2025-01-01 09:30:00  78.88
2025-01-02 09:30:00  75.88
2025-01-03 09:30:00  73.88
2025-01-04 09:30:00  72.88
2025-01-05 09:30:00  71.88
2025-01-06 09:30:00  71.88

In [14]:
df.index

DatetimeIndex(['2025-01-01 09:30:00', '2025-01-02 09:30:00',
               '2025-01-03 09:30:00', '2025-01-04 09:30:00',
               '2025-01-05 09:30:00', '2025-01-06 09:30:00'],
              dtype='datetime64[us]', name='Date', freq=None)

Two types of DateTime objects in python

1. Naive (No timezone awareness)
2. Time zone aware datetime

In [24]:
df= df.tz_localize('America/New_York')

In [20]:
df

                           Price
Date
2025-01-01 09:30:00-05:00  78.88
2025-01-02 09:30:00-05:00  75.88
2025-01-03 09:30:00-05:00  73.88
2025-01-04 09:30:00-05:00  72.88
2025-01-05 09:30:00-05:00  71.88
2025-01-06 09:30:00-05:00  71.88

In [25]:
# convert the timezone to UTC
df_utc = df.tz_convert('UTC')
df_utc

                           Price
Date
2025-01-01 14:30:00+00:00  78.88
2025-01-02 14:30:00+00:00  75.88
2025-01-03 14:30:00+00:00  73.88
2025-01-04 14:30:00+00:00  72.88
2025-01-05 14:30:00+00:00  71.88
2025-01-06 14:30:00+00:00  71.88

In [31]:
df_india = df.tz_convert('Asia/Kolkata')
df_india

                           Price
Date
2025-01-01 20:00:00+05:30  78.88
2025-01-02 20:00:00+05:30  75.88
2025-01-03 20:00:00+05:30  73.88
2025-01-04 20:00:00+05:30  72.88
2025-01-05 20:00:00+05:30  71.88
2025-01-06 20:00:00+05:30  71.88

In [ ]:
df.index= df.index.tz_convert('Asia/Kolkata')
df

# does the same thing as above

                           Price
Date
2025-01-01 20:00:00+05:30  78.88
2025-01-02 20:00:00+05:30  75.88
2025-01-03 20:00:00+05:30  73.88
2025-01-04 20:00:00+05:30  72.88
2025-01-05 20:00:00+05:30  71.88
2025-01-06 20:00:00+05:30  71.88

In [ ]:
rng = pd.date_range('2025-01-01', periods=6, freq='h')
rng
# by default it is naive, meaning it has no timezone information.
#  We can localize it to a specific timezone using the tz_localize method:
# datetime64[us] means microsecond precision,

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 01:00:00',
               '2025-01-01 02:00:00', '2025-01-01 03:00:00',
               '2025-01-01 04:00:00', '2025-01-01 05:00:00'],
              dtype='datetime64[us]', freq='h')

In [34]:
rng = pd.date_range('2025-01-01', periods=6, freq='h', tz='Asia/Kolkata')
rng

DatetimeIndex(['2025-01-01 00:00:00+05:30', '2025-01-01 01:00:00+05:30',
               '2025-01-01 02:00:00+05:30', '2025-01-01 03:00:00+05:30',
               '2025-01-01 04:00:00+05:30', '2025-01-01 05:00:00+05:30'],
              dtype='datetime64[us, Asia/Kolkata]', freq='h')

In [36]:
s = pd.Series(range(len(rng)), index=rng)
s

2025-01-01 00:00:00+05:30    0
2025-01-01 01:00:00+05:30    1
2025-01-01 02:00:00+05:30    2
2025-01-01 03:00:00+05:30    3
2025-01-01 04:00:00+05:30    4
2025-01-01 05:00:00+05:30    5
Freq: h, dtype: int64

In [39]:
b= s.tz_convert('America/New_York')
b

2024-12-31 13:30:00-05:00    0
2024-12-31 14:30:00-05:00    1
2024-12-31 15:30:00-05:00    2
2024-12-31 16:30:00-05:00    3
2024-12-31 17:30:00-05:00    4
2024-12-31 18:30:00-05:00    5
Freq: h, dtype: int64

tz_localize() = tell Pandas what timezone the datetime is already in. So for the first time we will use this only to let DF knw its Timezone
tz_convert() = change an already timezone-aware datetime to another timezone.

In [42]:
m = s.tz_convert('Asia/Shanghai')
m

2025-01-01 02:30:00+08:00    0
2025-01-01 03:30:00+08:00    1
2025-01-01 04:30:00+08:00    2
2025-01-01 05:30:00+08:00    3
2025-01-01 06:30:00+08:00    4
2025-01-01 07:30:00+08:00    5
Freq: h, dtype: int64

In [ ]:
b+m

# it will first convert both the b and m into utc and then do the arithemetic

2024-12-31 18:30:00+00:00     0
2024-12-31 19:30:00+00:00     2
2024-12-31 20:30:00+00:00     4
2024-12-31 21:30:00+00:00     6
2024-12-31 22:30:00+00:00     8
2024-12-31 23:30:00+00:00    10
Freq: h, dtype: int64