it helps in calculating the change in certain amount of days

In [1]:
import pandas as pd

df = pd.DataFrame({
    'Price': [178.88, 175.88, 173.88, 172.88, 171.88, 171.88]
}, index=pd.to_datetime([
    '2025-01-01 09:30:00',
    '2025-01-02 09:30:00',
    '2025-01-03 09:30:00',
    '2025-01-04 09:30:00',
    '2025-01-05 09:30:00',
    '2025-01-06 09:30:00'
]))

df.index.name = 'Date'

df

                      Price
Date
2025-01-01 09:30:00  178.88
2025-01-02 09:30:00  175.88
2025-01-03 09:30:00  173.88
2025-01-04 09:30:00  172.88
2025-01-05 09:30:00  171.88
2025-01-06 09:30:00  171.88

In [ ]:
df.shift(2)
# will shift the data point in the right hand side

                      Price
Date
2025-01-01 09:30:00     NaN
2025-01-02 09:30:00     NaN
2025-01-03 09:30:00  178.88
2025-01-04 09:30:00  175.88
2025-01-05 09:30:00  173.88
2025-01-06 09:30:00  172.88

In [8]:
# left shifting

df.shift(-2)

                      Price
Date
2025-01-01 09:30:00  173.88
2025-01-02 09:30:00  172.88
2025-01-03 09:30:00  171.88
2025-01-04 09:30:00  171.88
2025-01-05 09:30:00     NaN
2025-01-06 09:30:00     NaN

In [11]:
df['previous_day_price']= df['Price'].shift(1)
df

                      Price  previous_day_price
Date
2025-01-01 09:30:00  178.88                 NaN
2025-01-02 09:30:00  175.88              178.88
2025-01-03 09:30:00  173.88              175.88
2025-01-04 09:30:00  172.88              173.88
2025-01-05 09:30:00  171.88              172.88
2025-01-06 09:30:00  171.88              171.88

In [13]:
df['1 day price_change'] = df['Price'] - df['previous_day_price']
df

                      Price  previous_day_price  1 day price_change
Date
2025-01-01 09:30:00  178.88                 NaN                 NaN
2025-01-02 09:30:00  175.88              178.88                -3.0
2025-01-03 09:30:00  173.88              175.88                -2.0
2025-01-04 09:30:00  172.88              173.88                -1.0
2025-01-05 09:30:00  171.88              172.88                -1.0
2025-01-06 09:30:00  171.88              171.88                 0.0

In [16]:
df['5day //% return '] = (df['Price']- df['Price'].shift(5))*100/df['Price'].shift(5)
df

,Price,previous_day_price,1 day price_change,5day //% return
Date,,,,
2025-01-01 09:30:00,178.88,NaN,NaN,NaN
2025-01-02 09:30:00,175.88,178.88,-3.0,NaN
2025-01-03 09:30:00,173.88,175.88,-2.0,NaN
2025-01-04 09:30:00,172.88,173.88,-1.0,NaN
2025-01-05 09:30:00,171.88,172.88,-1.0,NaN
2025-01-06 09:30:00,171.88,171.88,0.0,-3.913238

shifting the index

In [17]:
df = df['Price']
df

Date
2025-01-01 09:30:00    178.88
2025-01-02 09:30:00    175.88
2025-01-03 09:30:00    173.88
2025-01-04 09:30:00    172.88
2025-01-05 09:30:00    171.88
2025-01-06 09:30:00    171.88
Name: Price, dtype: float64

In [25]:
df.index

DatetimeIndex(['2025-01-01 09:30:00', '2025-01-02 09:30:00',
               '2025-01-03 09:30:00', '2025-01-04 09:30:00',
               '2025-01-05 09:30:00', '2025-01-06 09:30:00'],
              dtype='datetime64[us]', name='Date', freq=None)

In [29]:
df.index.freq = pd.infer_freq(df.index)
df.index

DatetimeIndex(['2025-01-01 09:30:00', '2025-01-02 09:30:00',
               '2025-01-03 09:30:00', '2025-01-04 09:30:00',
               '2025-01-05 09:30:00', '2025-01-06 09:30:00'],
              dtype='datetime64[us]', name='Date', freq='D')

In [30]:
df_index= pd.date_range('2025-01-01 09:30:00', periods=6, freq ='D')
df.index

DatetimeIndex(['2025-01-01 09:30:00', '2025-01-02 09:30:00',
               '2025-01-03 09:30:00', '2025-01-04 09:30:00',
               '2025-01-05 09:30:00', '2025-01-06 09:30:00'],
              dtype='datetime64[us]', name='Date', freq='D')

In [33]:
df.shift(1, freq='D')

Date
2025-01-02 09:30:00    178.88
2025-01-03 09:30:00    175.88
2025-01-04 09:30:00    173.88
2025-01-05 09:30:00    172.88
2025-01-06 09:30:00    171.88
2025-01-07 09:30:00    171.88
Freq: D, Name: Price, dtype: float64